services:
  doctrine.dbal.connection_factory.decorator.jaeger:
    class: Doctrine\DBAL\Jaeger\Decorator\JaegerConnectionFactoryDecorator
    decorates: doctrine.dbal.connection_factory
    arguments: ['@doctrine.dbal.connection_factory.decorator.jaeger.inner', '@jaeger.tracer']
  doctrine.dbal.connection_factory.wrapper.jaeger:
    class: Doctrine\DBAL\Jaeger\Wrapper\JaegerConnectionWrapperFactory
    arguments: ['%doctrine.dbal.connection_factory.types%', '@jaeger.tracer']
